### ISSUE TITLE
Sprites not working

### ISSUE THREAD

**Issue by HoRnEyDvL** [Team-Resurgent/Nexgen-Public#10]
Sprites will not show on screen. 
No error  shown app rans as normal.

--************************************************************************************************ 
-- Define & Load Sprite Sheet.
--************************************************************************************************

local sheetTextureId = graphics.loadTexture("assets:images\\sprites\\sprite-sheet.png")
local sheetMeshId = graphics.createSheetMeshCollection(0, 0, 0, 64, 64, 1, 1)
graphics.bindMesh(sheetMeshId, 0)

local sheetCount = 0
-------------------------------------------------------------------------------------------------- 

function onRender(dt)

	sheetCount = sheetCount + (dt * 20)
	local sheetFrame = mathToInteger(sheetCount) % 255

-------------------------------------------------------------------------------------------------- 

-- Sprite
graphics.disableDepth()
graphics.activateTexture(sheetTextureId);
graphics.activateMesh(sheetMeshId, 0);
graphics.drawMesh(sheetFrame * 6, 6)
		
--------------------------------------------------------------------------------------------------

**Comment by EqUiNoX-Labs** [comment]
Expect issue due to bind changes where a sprite sheet contains a collection of quads and thus each quad needs binding... its not optimal but due to fact xbox OG  doesn't have long indices 

```
local sheetMeshId = graphics.createSheetMeshCollection(0, 0, 0, 64, 64, 1, 1)
local meshIndices = graphics.getMeshIndices(sheetMeshId)
for i, meshId in pairs(meshIndices) do
	graphics.bindMesh(sheetMeshId, meshId)
end
```

**Comment by EqUiNoX-Labs** [comment]
Ignore previous comment, I realized I could optimize sprite sheets as unlikely to need to be long indices and rolled back some changes I did and also fixed some underlying code which means sprite sheets now work

**Comment by HoRnEyDvL** [comment]
Ticket Closed, Issue resolved on 16/08/2021
