### ISSUE TITLE
Invalid characters when returning Path: in HTTP debug

### ISSUE THREAD

**Issue by HoRnEyDvL** [Team-Resurgent/Nexgen-Public#13]
When connecting to HTTP Debug output displays Invalid Characters as show below in bold.

INFO: Socket server init on port 80
INFO: done
INFO: Connected client: 1
INFO: Verb: 'GET', Path: **'쏠ỐƔ**', Query: ''
INFO: Prepared response
INFO: Send progress 0 of 31069
INFO: Send progress 31069 of 31069
INFO: Connected client: 1
INFO: Connected client: 2
INFO: Verb: 'GET', Path: **'쐐ỐƔ**', Query: ''
INFO: Prepared response
INFO: Send progress 0 of 197681
INFO: Connected client: 3
INFO: Verb: 'GET', Path: **'㲀ỈƔ'**, Query: ''
INFO: Prepared response
INFO: Send progress 0 of 13126
INFO: Connected client: 4
INFO: Send progress 197681 of 197681
INFO: Verb: 'GET', Path: **'੠᪤Ɣ'**, Query: ''
INFO: Prepared response
INFO: Send progress 0 of 37174
INFO: Connected client: 4
INFO: Send progress 13126 of 13126
INFO: Verb: 'GET', Path: **'䚀ỈƔ'**, Query: ''
INFO: Prepared response
INFO: Send progress 0 of 3839
INFO: Connected client: 4
INFO: Send progress 37174 of 37174
INFO: Verb: 'GET', Path: **'깐ỐƔ'**, Query: ''
INFO: Prepared response

**Comment by EqUiNoX-Labs** [comment]
Fixed

**Comment by HoRnEyDvL** [comment]
Fix Tested & Confirmed Working.

INFO: Connected client: 1
INFO: Verb: 'GET', Path: '/index.html', Query: ''
INFO: Prepared response
INFO: Send progress 0 of 31069
INFO: Send progress 31069 of 31069
INFO: Connected client: 1
INFO: Connected client: 2
INFO: Verb: 'GET', Path: '/css/styles.css', Query: ''
INFO: Prepared response
INFO: Send progress 0 of 197681
INFO: Connected client: 3
INFO: Verb: 'GET', Path: '/assets/mail/jqBootstrapValidation.js', Query: ''
INFO: Prepared response
INFO: Send progress 0 of 37174
INFO: Connected client: 4
INFO: Send progress 197681 of 197681
INFO: Verb: 'GET', Path: '/assets/mail/contact_me.js', Query: ''
