### ISSUE TITLE
Ftp Causes crash on connection ( **_localtime64**(...) returned nullptr.)

### ISSUE THREAD

**Issue by HoRnEyDvL** [Team-Resurgent/Nexgen-Public#14]
FTP causes Nexgen to crash.

WARNING: Could not create socket on port 6000, trying to find next available.

INFO: SocketSendString = 227 Entering Passive Mode (192,168,1,166,112,23)

Exception thrown: read access violation.
**_localtime64**(...) returned nullptr.

**Comment by EqUiNoX-Labs** [comment]
Should be fixed now, issue was down to partial mac portying of code

**Comment by HoRnEyDvL** [comment]
Fix has been tested & confirmed working.

No more crashing .

![image](https://user-images.githubusercontent.com/73101201/134111018-dd0090be-287e-47fe-ae6e-a25c923d0122.png)
