### ISSUE TITLE
Some font files wont load.

### ISSUE THREAD

**Issue by HoRnEyDvL** [Team-Resurgent/Nexgen-Public#2]
Some fonts wont load & cause Engine to crash with error.

Exception thrown: read access violation.
this was nullptr.

Attached sample font that crashes.
[fonts.zip](https://github.com/Team-Resurgent/Nexgen-Public/files/6915968/fonts.zip)

**Comment by EqUiNoX-Labs** [comment]
Issue was due to some fonts not containing kerning info, fix was to ignore if doesn't exist.
