### ISSUE TITLE
Skin Not Working on OG (xboxog)

### ISSUE THREAD

**Issue by HoRnEyDvL** [Team-Resurgent/Nexgen-Public#24]
Font loading having issues please refer to attached screenshot

![image](https://user-images.githubusercontent.com/73101201/134127697-008cad8a-37b7-4ee2-868e-9309ed27fa53.png)

**Comment by EqUiNoX-Labs** [comment]
Fixed: was calculating primitive count incorrectly based on vertices rather than indices

**Comment by HoRnEyDvL** [comment]
![image](https://user-images.githubusercontent.com/73101201/134635692-d4d0ea16-4c8b-48e6-b43c-a9427106eb0c.png)
Issue Resolved OG Build 24/09/2021
