### ISSUE TITLE
Ability to scale images without Bluring (AmyGrrl)

### ISSUE THREAD

**Issue by HoRnEyDvL** [Team-Resurgent/Nexgen-Public#26]
Feature request

**Comment by EqUiNoX-Labs** [comment]
Added nearest pixel filtering

**Comment by HoRnEyDvL** [comment]
graphics.Filter['Nearest']
graphics.Filter['Linear']

Example:
graphics.drawNinePatch(layerID, vector3.new(background.x, background.y, 0.0), renderGetWidth(), renderGetHeight(), 0.0, 0.0, graphics.Filter['Nearest'])
 
graphics.drawNinePatch(layerID, direction, renderGetWidth(), renderGetHeight(), 0.0, 0.0, graphics.Filter['Nearest'])
