### ISSUE TITLE
Calculation size of loaded image

### ISSUE THREAD

**Issue by risk510** [Team-Resurgent/Nexgen-Public#7]
Ability to calculate the width & height of loaded image in Lua

**Comment by EqUiNoX-Labs** [comment]
Exposed graphics.getTextureSize(TextureId)

**Comment by HoRnEyDvL** [comment]
Tested And working, Ticket now closed.

local PlayerMiddleImg = graphics.loadTexture("assets:images\\game\\planemiddle.png")

ImageWidth,ImageHeight = graphics.getTextureSize(PlayerMiddleImg)

print (ImageWidth .." " .. ImageHeight)


Debug Screen Results
INFO: 118.0 84.0
