### ISSUE TITLE
Multiple fonts do not work correctly

### ISSUE THREAD

**Issue by HoRnEyDvL** [Team-Resurgent/Nexgen-Public#8]
We are unable to load multiple fonts, Engine will use last loaded file even though we separate it by name.

Example:
fontId = graphics.loadFont("assets:fonts\\MobileFont.fnt")
fontId2 = graphics.loadFont("assets:fonts\\Arial_Black_16px.fnt")

graphics.drawFont(fontId, physicalTextPosition, "Physical Memory: " .. maths.toInteger(totalPhysical / 1024) .." KB" )
graphics.drawFont(fontId2, physicalTextPosition, "Physical Memory: " .. maths.toInteger(totalPhysical) .." B" )

Will render both lines using last loaded font.

**Comment by EqUiNoX-Labs** [comment]
Fixed: font data was being stored as static and thus secondary font info was overriding primary

**Comment by HoRnEyDvL** [comment]
Ticket Closed, Issue resolved on 16/08/2021
